ASSIGNMENT-1 NUMPY

Name: Arman Garg

Roll_no: 102356002

Grp:P1B

In [1]:
import numpy as np

### 1. Reverse the NumPy array: `arr = np.array([1, 2, 3, 6, 4, 5])`

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


### 2. Compare the following numpy arrays:
`arr1 = np.array([[1, 2], [3, 4]])`

`arr2 = np.array([[1, 2], [3, 4]])`

In [7]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comparison = arr1 == arr2
print(comparison)

result = np.array_equal(arr1, arr2)
print("Arrays equal?:",result)

[[ True  True]
 [ True  True]]
Arrays equal?: True


### 3. Find the most frequent value and their indice(s) in the following arrays:
i. `x = np.array([1,2,3,4,5,1,2,1,1,1])`

In [9]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)

most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)

print("Array x:", x)
print("Most Frequent:", most_frequent)
print("Indices:", indices)

Array x: [1 2 3 4 5 1 2 1 1 1]
Most Frequent: 1
Indices: (array([0, 5, 7, 8, 9]),)


### 3. Find the most frequent value and their indice(s) in the following arrays:
ii. `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])`

In [12]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)

print("Array y:", y)
print("Most Frequent:", most_frequent)
print("Indices:", indices)

Array y: [1 1 1 2 3 4 2 4 3 3]
Most Frequent: 1
Indices: (array([0, 1, 2]),)


### 4. For the array `gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')`,
find:

i. Sum of all elements

ii. Sum of all element’s row-wise

iii. Sum of all element’s column-wise

In [13]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg)

total_sum = np.sum(gfg)
print("Total Sum:", total_sum)

row_sum = np.sum(gfg, axis=1)
print("Row-wise Sum:\n", row_sum)

col_sum = np.sum(gfg, axis=0)
print("Column-wise Sum:\n", col_sum)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Total Sum: 45
Row-wise Sum:
 [[14]
 [16]
 [15]]
Column-wise Sum:
 [[20  9 16]]
